<?php

namespace App\Filament\Resources\PembayaranRegulers\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class PembayaranRegulersTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('pembayaran_mhs_baru_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('thn_akademik_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('semester_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('prodi_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('konsentrasi_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('angkatan')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('jenis_keluar_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('status_aktif_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WTGK')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WCTA')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WREG')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WIPK')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WIPU')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WIPF')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WIKT')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WSKS1')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WSKS2')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WBM')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('WTUM')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BTGK')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BCTA')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BREG')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BIPK')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BIPU')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BIPF')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BIKT')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BSKS1')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BSKS2')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BBM')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('BTUM')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('STGK')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SCTA')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SREG')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SIPK')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SIPU')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SIPF')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SIKT')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SSKS1')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SSKS2')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('SBM')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('STUM')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('JWR')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('JBR')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('JSR')
                    ->numeric()
                    ->sortable(),
                IconColumn::make('status')
                    ->boolean(),
                IconColumn::make('status_1')
                    ->boolean(),
                IconColumn::make('status_2')
                    ->boolean(),
                IconColumn::make('lulus')
                    ->boolean(),
                IconColumn::make('status_ganjil')
                    ->boolean(),
                IconColumn::make('status_genap')
                    ->boolean(),
                IconColumn::make('status_aktivasi_ganjil')
                    ->boolean(),
                IconColumn::make('status_aktivasi_genap')
                    ->boolean(),
                IconColumn::make('status_cicilan_ikt_1')
                    ->boolean(),
                IconColumn::make('status_cicilan_ikt_2')
                    ->boolean(),
                IconColumn::make('status_cicilan_ipu_1')
                    ->boolean(),
                IconColumn::make('status_cicilan_ipu_2')
                    ->boolean(),
                IconColumn::make('status_cicilan_sk1_1')
                    ->boolean(),
                IconColumn::make('status_cicilan_sk2_2')
                    ->boolean(),
                TextColumn::make('kerjasama_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
