<?php

namespace App\Filament\Resources\PembayaranMhsBarus\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class PembayaranMhsBaruForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('no_test')
                    ->required(),
                TextInput::make('npm'),
                TextInput::make('nama')
                    ->required(),
                TextInput::make('thn_akademik')
                    ->required(),
                Toggle::make('semester')
                    ->required(),
                TextInput::make('gelombang')
                    ->required(),
                TextInput::make('tingkat')
                    ->required(),
                TextInput::make('prodi')
                    ->required(),
                TextInput::make('konsentrasi')
                    ->required(),
                TextInput::make('angkatan')
                    ->required(),
                TextInput::make('ket')
                    ->required(),
                TextInput::make('WTGK')
                    ->required()
                    ->numeric(),
                TextInput::make('WCTA')
                    ->required()
                    ->numeric(),
                TextInput::make('WREG')
                    ->required()
                    ->numeric(),
                TextInput::make('WUPK')
                    ->required()
                    ->numeric(),
                TextInput::make('WUPU')
                    ->required()
                    ->numeric(),
                TextInput::make('WUPF')
                    ->required()
                    ->numeric(),
                TextInput::make('WUKT')
                    ->required()
                    ->numeric(),
                TextInput::make('WSKS1')
                    ->required()
                    ->numeric(),
                TextInput::make('WSKS2')
                    ->required()
                    ->numeric(),
                TextInput::make('WBM')
                    ->required()
                    ->numeric(),
                TextInput::make('WTUM')
                    ->required()
                    ->numeric(),
                TextInput::make('BTGK')
                    ->required()
                    ->numeric(),
                TextInput::make('BCTA')
                    ->required()
                    ->numeric(),
                TextInput::make('BREG')
                    ->required()
                    ->numeric(),
                TextInput::make('BUPK')
                    ->required()
                    ->numeric(),
                TextInput::make('BUPU')
                    ->required()
                    ->numeric(),
                TextInput::make('BUPF')
                    ->required()
                    ->numeric(),
                TextInput::make('BUKT')
                    ->required()
                    ->numeric(),
                TextInput::make('BSKS1')
                    ->required()
                    ->numeric(),
                TextInput::make('BSKS2')
                    ->required()
                    ->numeric(),
                TextInput::make('BBM')
                    ->required()
                    ->numeric(),
                TextInput::make('BTUM')
                    ->required()
                    ->numeric(),
                TextInput::make('STGK')
                    ->required()
                    ->numeric(),
                TextInput::make('SCTA')
                    ->required()
                    ->numeric(),
                TextInput::make('SREG')
                    ->required()
                    ->numeric(),
                TextInput::make('SUPK')
                    ->required()
                    ->numeric(),
                TextInput::make('SUPU')
                    ->required()
                    ->numeric(),
                TextInput::make('SUPF')
                    ->required()
                    ->numeric(),
                TextInput::make('SUKT')
                    ->required()
                    ->numeric(),
                TextInput::make('SSKS1')
                    ->required()
                    ->numeric(),
                TextInput::make('SSKS2')
                    ->required()
                    ->numeric(),
                TextInput::make('SBM')
                    ->required()
                    ->numeric(),
                TextInput::make('STUM')
                    ->required()
                    ->numeric(),
                TextInput::make('JWR')
                    ->required()
                    ->numeric(),
                TextInput::make('JBR')
                    ->required()
                    ->numeric(),
                TextInput::make('JSR')
                    ->required()
                    ->numeric(),
                TextInput::make('status')
                    ->default('0'),
                TextInput::make('status_1')
                    ->required()
                    ->default('0'),
                TextInput::make('status_2')
                    ->required()
                    ->default('0'),
                TextInput::make('jum_sks')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('jenis')
                    ->required(),
                Toggle::make('kategori')
                    ->required(),
                TextInput::make('status_3'),
                Toggle::make('alumni')
                    ->required(),
                Toggle::make('status_skema_id')
                    ->required(),
                TextInput::make('kerjasama_id')
                    ->required()
                    ->numeric()
                    ->default(0),
            ]);
    }
}
