<?php

namespace App\Filament\Resources\PembayaranRegulers\Schemas;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class PembayaranRegulerForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('pembayaran_mhs_baru_id')
                    ->required()
                    ->numeric(),
                TextInput::make('thn_akademik_id')
                    ->required()
                    ->numeric(),
                TextInput::make('semester_id')
                    ->required()
                    ->numeric(),
                TextInput::make('prodi_id')
                    ->required()
                    ->numeric(),
                TextInput::make('konsentrasi_id')
                    ->required()
                    ->numeric()
                    ->default(0),
                TextInput::make('angkatan')
                    ->required()
                    ->numeric(),
                TextInput::make('jenis_keluar_id')
                    ->required()
                    ->numeric(),
                TextInput::make('status_aktif_id')
                    ->required()
                    ->numeric(),
                TextInput::make('WTGK')
                    ->required()
                    ->numeric(),
                TextInput::make('WCTA')
                    ->required()
                    ->numeric(),
                TextInput::make('WREG')
                    ->required()
                    ->numeric(),
                TextInput::make('WIPK')
                    ->required()
                    ->numeric(),
                TextInput::make('WIPU')
                    ->required()
                    ->numeric(),
                TextInput::make('WIPF')
                    ->required()
                    ->numeric(),
                TextInput::make('WIKT')
                    ->required()
                    ->numeric(),
                TextInput::make('WSKS1')
                    ->required()
                    ->numeric(),
                TextInput::make('WSKS2')
                    ->required()
                    ->numeric(),
                TextInput::make('WBM')
                    ->required()
                    ->numeric(),
                TextInput::make('WTUM')
                    ->required()
                    ->numeric(),
                TextInput::make('BTGK')
                    ->required()
                    ->numeric(),
                TextInput::make('BCTA')
                    ->required()
                    ->numeric(),
                TextInput::make('BREG')
                    ->required()
                    ->numeric(),
                TextInput::make('BIPK')
                    ->required()
                    ->numeric(),
                TextInput::make('BIPU')
                    ->required()
                    ->numeric(),
                TextInput::make('BIPF')
                    ->required()
                    ->numeric(),
                TextInput::make('BIKT')
                    ->required()
                    ->numeric(),
                TextInput::make('BSKS1')
                    ->required()
                    ->numeric(),
                TextInput::make('BSKS2')
                    ->required()
                    ->numeric(),
                TextInput::make('BBM')
                    ->required()
                    ->numeric(),
                TextInput::make('BTUM')
                    ->required()
                    ->numeric(),
                TextInput::make('STGK')
                    ->required()
                    ->numeric(),
                TextInput::make('SCTA')
                    ->required()
                    ->numeric(),
                TextInput::make('SREG')
                    ->required()
                    ->numeric(),
                TextInput::make('SIPK')
                    ->required()
                    ->numeric(),
                TextInput::make('SIPU')
                    ->required()
                    ->numeric(),
                TextInput::make('SIPF')
                    ->required()
                    ->numeric(),
                TextInput::make('SIKT')
                    ->required()
                    ->numeric(),
                TextInput::make('SSKS1')
                    ->required()
                    ->numeric(),
                TextInput::make('SSKS2')
                    ->required()
                    ->numeric(),
                TextInput::make('SBM')
                    ->required()
                    ->numeric(),
                TextInput::make('STUM')
                    ->required()
                    ->numeric(),
                TextInput::make('JWR')
                    ->required()
                    ->numeric(),
                TextInput::make('JBR')
                    ->required()
                    ->numeric(),
                TextInput::make('JSR')
                    ->required()
                    ->numeric(),
                Toggle::make('status')
                    ->required(),
                Toggle::make('status_1')
                    ->required(),
                Toggle::make('status_2')
                    ->required(),
                Toggle::make('lulus')
                    ->required(),
                Toggle::make('status_ganjil')
                    ->required(),
                Toggle::make('status_genap')
                    ->required(),
                Toggle::make('status_aktivasi_ganjil')
                    ->required(),
                Toggle::make('status_aktivasi_genap')
                    ->required(),
                Toggle::make('status_cicilan_ikt_1')
                    ->required(),
                Toggle::make('status_cicilan_ikt_2')
                    ->required(),
                Toggle::make('status_cicilan_ipu_1')
                    ->required(),
                Toggle::make('status_cicilan_ipu_2')
                    ->required(),
                Toggle::make('status_cicilan_sk1_1')
                    ->required(),
                Toggle::make('status_cicilan_sk2_2')
                    ->required(),
                TextInput::make('kerjasama_id')
                    ->required()
                    ->numeric()
                    ->default(0),
            ]);
    }
}
